name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 'v1.x'

      - name: Check Formatting
        run: deno fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 'v1.x'

      - name: Setup Depot Tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        
      - name: Build Skia
        run: export PATH=$(pwd)/depot_tools:$PATH && deno task build-skia

      - name: Build Native Library
        run: mkdir ./native/build && deno task build

      - name: Run Tests
        run: deno task test
